global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "prometheus-bogor-node"
    static_configs:
      - targets:
          - "localhost:9100"
        labels:
          cabang: "bogor"

  - job_name: "nas-bogor-node"
    static_configs:
      - targets:
          - "10.2.0.5:9100"
        labels:
          cabang: "NAS Bogor"

  - job_name: "app-bogor-node"
    static_configs:
      - targets:
          - "10.2.0.10:9100"
        labels:
          cabang: "App Bogor"

  - job_name: "app-bogor-postgres"
    static_configs:
      - targets:
          - "10.2.0.10:9187"
        labels:
          cabang: "Postgres App Bogor"
